### ISSUE TITLE
using GPIO pins

### ISSUE THREAD

**Issue by Partizan7676** [Maxmudjon/homebridge-video-doorbell-button#1]
Can you make support for using GPIO pins?

- for button
- for control lock(better if it will be with setting for time how much relay will hold lock - eltctromagnetic or electromecanic)
- sensor to control door state.

**Comment by Maxmudjon** [comment]
Yes of course I can. Will do with the next version

**Comment by Maxmudjon** [comment]
released new version with lock and gpio button

> Can you make support for using GPIO pins?
> 
> * for button
> * for control lock(better if it will be with setting for time how much relay will hold lock - eltctromagnetic or electromecanic)
> * sensor to control door state.
